---
title: "On Writing Abstract"
author: "Dongweon Shin"
date: "March 26 2025"

format: 
  revealjs:
    css: styles.css
    mathjax: 
      url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
      macros:
        "\\eulerNum": "{\\mathit{#1}}"

project:
  type: website
  output-dir: docs


---
## Recap




## PREPARING AN ABSTRACT FOR A SCIENTIFIC MEETING

Preparing an abstract serves several other important functions.

- It forces you to **set aside data gathering for a while** and synthesize your results. Often, that turns out to be a useful process. 
It can clarify the direction of your research. You may discover, for example, that the reason you are having such a difficult time summarizing your work in a single abstract is that you are actually doing two or more distinct projects. 
- You may realize that essential parts of the study are incomplete or that more subjects are needed.
- DO NOT delay writing the full manuscript while waiting to hear whether an abstract has been accepted.

Most of all, submitting an abstract to a meeting will also provide you with a valuable clue as to the merit of your work. 
The response to your manuscript will usually parallel the response to the abstract. 

## GETTING STARTED ON A MEETING ABSTRACT

In the simplest form, an abstract consists of four parts: 

(i) a sentence or two of introduction, 

(ii) the essential aspects of the study's methods, 
(iii) the main results of the study, and 

(iv) a brief statement of your conclusions about the meaning of the study. (Each of these four sections is discussed in more detail in Chapters 3, 4, 5, and 8.) 

In all sections, brevity is essential. It is often helpful to write the parts separately and then string them together at the end. Occasionally, a meeting requires that you submit a structured abstract, following specific rules on content.


## Introduction
The introduction answers the question "Why was it important to do this study?" by presenting what is known and not known, about the research topic. Sometimes, this part of an abstract is called the background: Do not make the common mistake of assuming that the answer is obvious. Just because you have spent a few years working on a problem does not mean that a reviewer or reader will be nearly as knowledgeable. Sometimes, stating the limitations of previous studies helps: "While many family practitioners believe they spend more time with depressed patients than do internists, this has never been evaluated in actual practice."
The introduction should be written in plain English, without jargon, run-on sentences, abbreviations, or acronyms. You want to make it as easy as possible for the reviewer to read on. The introduction usually ends with a one-sentence description of the research question, in the form of the study's objective.

## Methods
The methods section of the abstract should describe the study design, who was studied, what you measured, and how you analyzed the data. If it matters, you should mention where the subjects came from and how they were selected. Specify the number of subjects, by group if appropriate. All important measurement techniques should be described. You can leave out obvious methods ("Subjects were asked their age and sex"), as well as intricate details, unless they absolutely matter.
Results
Make sure you emphasize the main finding of the study. Concentrate on various aspects of that single result, such as the effects of adjusting for potential confounders,


of the meeting have decided to accept the same proportion of abstracts in each area. If a meeting has a scientific theme, and your research fits that theme, then take advantage of that, since the meeting organizers will be looking for abstracts in that area.
Some meetings, especially international ones, may accept all, or nearly all, the abstracts submitted. In general, the higher the registration fee, the more likely an abstract will be accepted. For many groups, the annual or biennial meeting is a big money-making opportunity, particularly if there is extensive corporate sponsor-ship. That is why membership in the meeting's sponsoring organization is often a prerequisite for submission of an abstract. The more abstracts submitted, the more scientists who need to join the society; the more abstracts accepted, the more scientists who will pay the registration fee, attend the meeting, and be available to corporate representatives.
How Can I Make Sure That My Abstract Stands Out?
A review panel usually consists of between three and ten reviewers, each of whom may receive 50 to 100, or sometimes more, abstracts to review. Reviewers can spend only a few minutes with each abstract. They are looking for abstracts that seem to belong at the meeting, such as those with hot topics, large sample sizes, or impressive statistics. In their haste, reviewers may not notice subtly elegant design features or novel methodologic approaches unless you point them out. If your abstract has one of these attributes, say so:
Although many have advocated ..., this has never been done. We therefore performed the first. ...
To avoid these problems, we developed a new methodology that. ...
Reviewers may miss important results, especially if they are written in jargon. Use plain English to emphasize them:
Change:
In multivariable logistic regression analyses, there was a statistically significant linear association between serum HDL cholesterol levels measured in stored serum samples obtained at the time of enrollment and the odds of being diagnosed with an aortic aneurysm (P < 0.001) during follow-up.
To:
HDL cholesterol was an independent risk factor for aortic vascular disease, such that subjects with serum levels < 35 mg/dL had 3 times (95% Cl: 1.4 - 7) the risk of developing an aortic aneurysm than those with levels > 55 mg/dL.



## Why Abstracts are Rejected

Reviewers look for reasons to reject an abstract, in part because it is usually easier to identify obviously bad work than to select really good work. 
But reviewers will usually not have time to notice subtle examples of bias or confounding. Several grounds for quick rejection of an abstract are particularly common.



Dull Topic with Lots of Previous Research.
judge an abstract's originality. You must include something new, or carefully specify how what you did is better than previous work. If your work is strictly confirmatory, then indicate why the confirmation was needed-for example, because only one or two prior studies had been done, or because the previous results were considered
controversial.
No Context for the Research. Never assume that the reviewers will be sufficiently familiar with your specific field of research to understand why it is important. Take one or two sentences at the beginning of the abstract to explain the background for the work, and take another sentence at the end to discuss the implications of your results.
Small Number of Subjects. Limited sample size is especially problematic if the results are nonsignificant. Remember, reviewers are looking for a reason to reject, and a study of only 5 or even 20 patients is an invitation to do so. All is not lost, however, if your or to conta ge he pains at can, hers why ine rescarch matter, you way,.
No Numbers, All Talk Most reviewers respond unfavorably to an abstract devoid of numbers, in part because it is not possible to tell whether the investigators studied one subject or 500, or whether they found anything of value. In some cases, abstracts lacking statistics fall in the same category. Numbers and statistics may not matter in your particular case (say, discovering a genetic defect that causes a rare disease), but your abstract will probably face an uphill battle.
All Numbers, No Words. Abstracts crammed with lists of numbers with no clear explanation are often rejected. Reviewers do not have the time to figure out what an abstract might have said had the authors made it interpretable. Moreover, any important results will get drowned out by the noise.
Too Short. This may seem silly, but an abstract that is much shorter than all the other submissions may not be accepted. It will look strange. Fill—or at least come close to filling —the box or the allocated number of words.
Sloppiness,
As with any submission, sloppiness in presentation will be inter-preted— and should be interpreted-as a cause for concern about the general quality of the work. Check for typographical errors, simple arithmetical mistakes, and misspelled names. Read the abstract aloud to someone else.
Looks Too Different from Other Abstracts. Find a copy of the previous year's abstracts, which are usually published as a journal supplement. Then compare the used? What sort of research questions seemed to be in favor?
plenary abstracts with what you plan to submit. For example, were figures


Phrases That Invite Rejection. There are two phrases that will almost always result in your abstract being rejected: "Data will be presented" and "Results will be discussed." Never include either of these phrases in an abstract unless you have been for the audience's benefit.
invited to make a presentation at the meeting and were asked to submit an abstract Too Many Abbreviations, Too Much Data. Lots of abbreviations and numbers may create the impression that you have done some real work, so your abstract may be less


likely to be rejected outright. But they also make it harder for the reviewer to figure out whether you have done anything exceptional, so the likelihood of getting a high rating is also diminished. Demonstrating to a reviewer that you have many results is not nearly as important as showing that you have one important result that merits an oral or plenary presentation.
Ten or Twenty P Values. An abstract that is full of P values is usually an abstract that lacks focus and effect sizes. Change a sentence such as "We found that fair skin (P < 0.05), sun exposure (P < 0.01), lack of use of sunscreen (P < 0.001), and residence in a beach community (P < 0.0001) were independently associated with skin cancer" into one that tells the reader what you found, and the strength of the association between each of these characteristics and skin cancer: "We identified
several independent risk factors for skin cancer: fair skin (odds ratio [OR] = 1.6;
95% confidence interval [CI]: 1.0 - 2.6), failure to use sunscreen (OR = 2.0; CI:
1.4 - 2.9), and living in a beach community (RR = 5.0; CI: 2.0 - 12). Each hour of
sun exposure per day increased the risk of skin cancer by 35% (95% CI: 10% - 66%)." The extra length leads to much greater clarity.
Overuse of Respectively. It is tempting to save space by listing variables, then the results followed by the word respectively: "The risks of glaucoma in white men, black men, Asian men, white women, black women, and Asian women were 8%, 12%, 6%, 4%, 6%, and 3%, respectively." This phrasing slows down and confuses the reader, who is forced to scan back and forth between the text and the numbers to figure out which ones go together. Reread the sentence in question, and you will see what I mean.
Instead of using "respectively," rephrase the sentence to keep the groups and the percentages together, and to provide some interpretation of the results: "Glaucoma was more common in men than women, and in blacks than in other racial groups.
The risks in men were 8% in whites, 12% in blacks, and 6% in Asians; in women, they were 4% in whites, 6% in blacks, and 3% in Asians."




#

The purpose of the abstract that accompanies a manuscript is straightforward: to present the basic substance of the study, and to entice the reader (and the reviewer) to read the manuscript. Keep it simple.
The most common mistakes are reusing a meeting abstract for a manuscript and using an abstract that is unnecessarily complicated. If your manuscript is accepted, almost everyone who is reading your abstract will have access to the full-length article; after all, it has been published. The same is true in the manuscript review process.
Even if someone is reading the abstract on the Internet, that person will either have access to a medical library or can write to you for a reprint.
Minor details should be omitted from the abstract (but most should be included in the text, of course). It is rarely necessary to mention the number of subjects with missing data, or the exact recruitment period, for example. There is rarely a need to describe your subjects in great detail (e.g., the age, sex, and race distribution) or to explain complicated findings. These are the reasons why the abstract for a paper is sometimes more appropriately called a summary.
Many journals now require that authors submit a structured abstract, with specific sections dictated by each journal's rules. Imposing a uniform framework ensures that all the key points are covered. Structured abstracts are just like ordinary abstracts, with one exception: They are rarely written in complete sentences. The basic parts -background, methods, results, and conclusions —remain, though some may be further divided into